### ISSUE TITLE
pressure drop in hydrogen pipelines 

### ISSUE THREAD

**Issue by Ahmedhassan676** [equinor/neqsimhome#3]
Hello,
First, thanks for the wonderful work you've all been doing and for this very interesting library. I've been trying to use and learn more about this tool for a couple of days and I faced an issue while trying to use the pipe method for a hydrogen line. the code returns the same inlet pressure and the viscosity row returns a "?" sign. the code works just fine when using methane instead of hydrogen.
I thought the problem is the flow rate but I checked the flow rate in other simulators and it should return an outlet pressure of about 12.1 bar.
my code is as follows:

import pandas as pd
import neqsim
from neqsim.thermo.thermoTools import *
from neqsim.process.processTools import *
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib inline

from neqsim import methods
from neqsim.thermo import fluid, TPflash
from neqsim.process import pipe, pipeline, clearProcess, stream, runProcess

#q = 5*24/(1000000)
q=0.1396
D = 3*25.4*0.001
# Start by creating a fluid in neqsim
fluid1 = fluid("pr")  # create a fluid using the SRK-Eo
fluid1.addComponent("hydrogen",(3*246.6)/3600)
fluid1.addComponent("ethane", (12.9*3)/3600)
fluid1.setMixingRule('classic')
fluid1.setTemperature(45, "C")
fluid1.setPressure(16, "bara")
fluid1.setTotalFlowRate(q, "MSm3/day")
#TPflash(fluid1)

stream1 = stream(fluid1)

deltaElevation = 0.0
pipeLength = 3000.0
roughness= 5.0e-5
diameter = D
clearProcess()
pipeSimple = pipe(stream1, pipeLength, deltaElevation, diameter, roughness)
runProcess()
print('pressure out of pipeline ', pipeSimple.getOutStream().getFluid().getPressure('bara'), '[bara]')
pd.DataFrame(printFrame(pipeSimple.getOutStream().getFluid()))

method = "friction theory"
fluid1.getPhase('gas').getPhysicalProperties().setViscosityModel(method)
fluid1.initProperties()
print("gas viscosity ", fluid1.getViscosity('cP'), " cP ", " metod: ", method)

**Comment by EvenSol** [comment]
Hei.
Great work!

It seems as the default viscosity method returns NaN for hydrogen (it worked for methane). I will look into it.

A workaround could be:

```
from neqsim.thermo import *
fluid1 = fluid("pr") # create a fluid using the SRK-Eo
fluid1.addComponent("hydrogen",(3246.6)/3600)
fluid1.addComponent("ethane", (12.93)/3600)
fluid1.setMixingRule('classic')
fluid1.setTemperature(45, "C")
fluid1.setPressure(16, "bara")
fluid1.setTotalFlowRate(q, "MSm3/day")
TPflash(fluid1)
method = "friction theory"
fluid1.getPhase('gas').getPhysicalProperties().setViscosityModel(method)


deltaElevation = 0.0
pipeLength = 3000.0
roughness= 5.0e-5
diameter = D

clearProcess()
stream1 = stream(fluid1)
pipeSimple = pipe(stream1, pipeLength, deltaElevation, diameter, roughness)
runProcess()

print('pressure out of pipeline ', pipeSimple.getOutStream().getFluid().getPressure('bara'), '[bara]')
pd.DataFrame(printFrame(pipeSimple.getOutStream().getFluid()))
```

**Comment by Ahmedhassan676** [comment]
Thanks!
